# Домашняя работа №1

## NumPy

Все задачи из блока ниже нужно решить, не используя циклов (`for`, `while`, `list comprehension`, `apply`, `np.vectorize`, `np.fromfunction` и так далее, создать новые объекты при помощи встроенноых `numpy` генераторов можно) в реализации. Также для каждой задачи нужно написать проверку: создать какой-то пример, написать для него решение и проверить, что реализованная функция для этого примера возвращает объект, который совпадает с решением. Например:

```python
example = np.eye(5)
solution = 2 * np.eye(5)

result = double_all_elements(example)
assert np.allclose(result, solution)
```

### Задание 1 (0.5 балла)

Реализуйте функцию, которая из двух векторов $X$ и $Y$ размерности $n$ строит матрицу размерности $(n, 2)$ ($n$ - произвольное)

### Задание 2  (0.5 балла)

Реализуйте функцию, которая для произвольной матрицы $X$ возвращает среднее значение положительных диагональных элементов

5.0

### Задание 3  (0.5 балла)

Реализуйте функцию, которая для произвольной матрицы $X$ и произвольного числа $k$ заменяет все диагональные элементы матрицы на $k$ (функция не должна ничего возвращать, только модифицировать заданную матрицу)

array([[100,   2,   3],
       [  4, 100,   6]])

### Задание 4  (0.5 балла)

Реализуйте функцию, которая проверяет, являются ли две матрицы $X$ и $Y$ одинаковыми (совпадают размерности и значения), если их преобразовать в вектор построчно (например, для `np.array([[0, 1, 2], [3, 4, 5]])` построчное преобразование в вектор - это `np.array([0, 1, 2, 3, 4, 5])`. 

Функция должна возвращать `True`, если матрицы одинаковые, иначе `False`.

False

### Задание 5  (1 балл)

Реализуйте функцию, которая для произвольной матрицы $X$ и произвольного числа k возвращает вектор, состоящий из тех значений $x_{ij}$, для которых верно равенство $(i + j) \bmod k = 0$

array([1, 3, 5, 7, 9])

### Задание 6 (1 балл)

В numpy пропущенное значение (`np.nan`) имеет тип `float`:

In [23]:
type(np.nan)

float

Из-за этого любой числовой массив, содержащий пропущенные значения, будет автоматически иметь тип `float`:

In [30]:
t = np.array([1, 2, 3, np.nan])
t

array([ 1.,  2.,  3., nan])

In [28]:
t.dtype

dtype('float64')

Реализуйте функцию, которая для произвольной матрицы $X$ будет заменять все пропущенные значения на среднее значение в соответствующей строке, округленное до целого. Также эта функция должна поменять тип матрицы с `float` на `int`, если она после этого преобразования состоит только из целых чисел (считаем, что `3.0` - это целое число). В этой задаче можно создать и вернуть новый объект.

### Задание 7 (1.5 балла)

С помощью библиотеки `numba` и декоратора `numba.njit` реализуйте функцию, которая для заданной матрицы, состоящей из положительных чисел, выполняет следующее:

1) Все нулевые элементы массива заменяются на случайное целое число от 0 до 100 (без создания копии массива);

2) Возвращает среднее значение квадратных корней элементов матрицы (то есть значение $K = \frac{1}{N\cdot M}\sum_{i=1}^N \sum_{j=1}^M \sqrt{x_{ij}}$);

Сравните скорость работы функции с декоратором и без декоратора. Попробуйте также задать разные значения `parallel` и `fastmath` при использовании декоратора. Опишите, как это влияет на скорость работы и попробуйте предположить, почему получаются такие результаты.

Матрица $X$ задана следующим образом:

In [2]:
X = np.random.randint(0, 1000, size=(1000, 100))

$\textbf{Важно:}$ Попробуйте решить задачу без использования циклов. Если не получается сделать решение без циклов, то приведите реализацию с циклами. Подробно опишите полученные результаты, за отсутствие интерпретации будут снижаться баллы.

## Pandas

Для выполнения следующих заданий нам потребуется датасет `iris`:

In [58]:
import pandas as pd
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Задание 1 (0.25 балла)

Для столбца `sepal_length` посчитайте среднее значение, среднее квадратичное отклонение и медиану по каждому классу из `species`.

### Задание 2 (0.25 балла)

Посчитайте количество строк в датасете, которое удовлетворяет условию: `species == 'setosa'` и `sepal_width > 3.2`

### Задание 3 (0.5 балла)

Реализуйте функцию, которая возвращает датасет, в котором нет строк с одновременно одинаковыми значениями `sepal_width` и `species`

### Задание 4 (0.5 балла)

Создайте новую колонку `width_on_length`, в которой значение формируется согласно правилу: 

* если species - `setosa`, то значение равно `sepal_width * sepal_length`; 
* если species - `versicolor`, то значение равно `1.5 * sepal_width * sepal_length / petal_length`;
* иначе `np.nan`

### Задание 5 (0.5 балла)

Реализуйте функцию, которая заполняет пропущенные значения в колонке `width_on_length` случайными `float` значениями от 10 до 30, сортирует строки по значению `width_on_length` по убыванию и после этого перенумеровывает индекс датасета (проверьте, чтобы после этих действий не появилось новых колонок).

##  Визуализация

В задачах на визуализацию обязательно подписывайте название графиков и осей, иначе будут снижаться баллы.

In [63]:
import seaborn as sns
import matplotlib.pylab as plt

### Задание 1 (0.5 балла)

Визуализируйте распределение width_on_length для каждого класса из `species` с помощью функции `sns.kdeplot` (для каждого класса - свой отдельный график).

### Задание 2 (0.5 балла)

Визуализируйте распределение width_on_length для каждого класса из `species` с помощью функции `sns.boxplot` (все классы изобразите на одном графике).

### Задание 3 (0.5 балла)

Постройте график зависимости `sepal_length` от `sepal_width` для класса `setosa` из `species` (в случае дублей в `sepal_width` - найдите среднее `sepal_length` для этого значения `sepal_width` и используйте его для построения графика)

### Задание 4 (1 балл)

Визуализируйте средние значения столбцов `sepal_length, sepal_width, petal_length, petal_width` для каждого класса из `species` в виде столбиковой диаграммы из любой библиотеки на ваш выбор, например `sns.barplot` или `pd.DataFrame.plot.bar` (изобразите все на одном графике).